spring.application.name=PayMoney
spring.datasource.url=jdbc:postgresql://localhost:5432/payflow
spring.datasource.username=postgres
spring.datasource.password=ayush@2105

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
logging.level.org.springframework.security=DEBUG
spring.jackson.time-zone=Asia/Kolkata
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
app.admin.email=${PAYMONEY_ADMIN_EMAIL}
app.admin.password=${PAYMONEY_ADMIN_PASSWORD}